/*
-- Query: select * 
from brand as b
left join model as m on b.id_brand = m.id_brand
left join variant as v on v.id_model = m.id_model
left join engine_variant as ev on ev.id_variant = v.id_variant
left join engine as E ON e.id_engine = ev.id_engine
left join fuel as fu on fu.id_fuel = e.id_fuel
left join variant_feature as vf on vf.id_variant = v.id_variant
left join feature as f on f.id_feature = vf.id_feature
order by v.id_variant
-- Date: 2024-03-05 22:38
*/
INSERT INTO `` (`id_brand`,`description`,`id_model`,`description`,`id_brand`,`id_variant`,`description`,`id_model`,`id_variant`,`id_engine`,`id_engine`,`description`,`id_fuel`,`transmission`,`capacity`,`power`,`cylinders`,`id_fuel`,`description`,`id_variant`,`id_feature`,`id_feature`,`description`) VALUES (4,'Lamborghini',74,'Urus',4,4,'Urus S',74,4,1,1,NULL,1,'Semi-Automatic',3996,650,8,1,'Petrol',NULL,NULL,NULL,NULL);
INSERT INTO `` (`id_brand`,`description`,`id_model`,`description`,`id_brand`,`id_variant`,`description`,`id_model`,`id_variant`,`id_engine`,`id_engine`,`description`,`id_fuel`,`transmission`,`capacity`,`power`,`cylinders`,`id_fuel`,`description`,`id_variant`,`id_feature`,`id_feature`,`description`) VALUES (4,'Lamborghini',74,'Urus',4,5,'Urus',74,5,2,2,NULL,1,'Semi-Automatic',3996,666,8,1,'Petrol',NULL,NULL,NULL,NULL);
INSERT INTO `` (`id_brand`,`description`,`id_model`,`description`,`id_brand`,`id_variant`,`description`,`id_model`,`id_variant`,`id_engine`,`id_engine`,`description`,`id_fuel`,`transmission`,`capacity`,`power`,`cylinders`,`id_fuel`,`description`,`id_variant`,`id_feature`,`id_feature`,`description`) VALUES (4,'Lamborghini',74,'Urus',4,6,'Urus Performante',74,6,2,2,NULL,1,'Semi-Automatic',3996,666,8,1,'Petrol',NULL,NULL,NULL,NULL);
INSERT INTO `` (`id_brand`,`description`,`id_model`,`description`,`id_brand`,`id_variant`,`description`,`id_model`,`id_variant`,`id_engine`,`id_engine`,`description`,`id_fuel`,`transmission`,`capacity`,`power`,`cylinders`,`id_fuel`,`description`,`id_variant`,`id_feature`,`id_feature`,`description`) VALUES (4,'Lamborghini',75,'Aventator',4,7,'Aventator',75,7,5,5,NULL,1,'Automatic',6498,378,12,1,'Petrol',NULL,NULL,NULL,NULL);
INSERT INTO `` (`id_brand`,`description`,`id_model`,`description`,`id_brand`,`id_variant`,`description`,`id_model`,`id_variant`,`id_engine`,`id_engine`,`description`,`id_fuel`,`transmission`,`capacity`,`power`,`cylinders`,`id_fuel`,`description`,`id_variant`,`id_feature`,`id_feature`,`description`) VALUES (4,'Lamborghini',75,'Aventator',4,8,'Aventator Roadster',75,8,6,6,NULL,1,'Manual',6498,740,12,1,'Petrol',NULL,NULL,NULL,NULL);
INSERT INTO `` (`id_brand`,`description`,`id_model`,`description`,`id_brand`,`id_variant`,`description`,`id_model`,`id_variant`,`id_engine`,`id_engine`,`description`,`id_fuel`,`transmission`,`capacity`,`power`,`cylinders`,`id_fuel`,`description`,`id_variant`,`id_feature`,`id_feature`,`description`) VALUES (4,'Lamborghini',75,'Aventator',4,9,'Aventator S',75,9,6,6,NULL,1,'Manual',6498,740,12,1,'Petrol',NULL,NULL,NULL,NULL);
INSERT INTO `` (`id_brand`,`description`,`id_model`,`description`,`id_brand`,`id_variant`,`description`,`id_model`,`id_variant`,`id_engine`,`id_engine`,`description`,`id_fuel`,`transmission`,`capacity`,`power`,`cylinders`,`id_fuel`,`description`,`id_variant`,`id_feature`,`id_feature`,`description`) VALUES (4,'Lamborghini',75,'Aventator',4,10,'Aventator SV',75,10,9,9,NULL,1,'Automatic Tiptronic',6498,740,12,1,'Petrol',NULL,NULL,NULL,NULL);
INSERT INTO `` (`id_brand`,`description`,`id_model`,`description`,`id_brand`,`id_variant`,`description`,`id_model`,`id_variant`,`id_engine`,`id_engine`,`description`,`id_fuel`,`transmission`,`capacity`,`power`,`cylinders`,`id_fuel`,`description`,`id_variant`,`id_feature`,`id_feature`,`description`) VALUES (4,'Lamborghini',75,'Aventator',4,11,'Aventator SV Roadster',75,11,9,9,NULL,1,'Automatic Tiptronic',6498,740,12,1,'Petrol',NULL,NULL,NULL,NULL);
INSERT INTO `` (`id_brand`,`description`,`id_model`,`description`,`id_brand`,`id_variant`,`description`,`id_model`,`id_variant`,`id_engine`,`id_engine`,`description`,`id_fuel`,`transmission`,`capacity`,`power`,`cylinders`,`id_fuel`,`description`,`id_variant`,`id_feature`,`id_feature`,`description`) VALUES (4,'Lamborghini',75,'Aventator',4,12,'Aventator SVJ',75,12,11,11,NULL,1,'Automatic Tiptronic',6498,566,12,1,'Petrol',NULL,NULL,NULL,NULL);
INSERT INTO `` (`id_brand`,`description`,`id_model`,`description`,`id_brand`,`id_variant`,`description`,`id_model`,`id_variant`,`id_engine`,`id_engine`,`description`,`id_fuel`,`transmission`,`capacity`,`power`,`cylinders`,`id_fuel`,`description`,`id_variant`,`id_feature`,`id_feature`,`description`) VALUES (4,'Lamborghini',75,'Aventator',4,13,'Aventator SVJ Roadster',75,13,25,25,NULL,1,'Semi-Automatic',6498,770,12,1,'Petrol',NULL,NULL,NULL,NULL);
INSERT INTO `` (`id_brand`,`description`,`id_model`,`description`,`id_brand`,`id_variant`,`description`,`id_model`,`id_variant`,`id_engine`,`id_engine`,`description`,`id_fuel`,`transmission`,`capacity`,`power`,`cylinders`,`id_fuel`,`description`,`id_variant`,`id_feature`,`id_feature`,`description`) VALUES (4,'Lamborghini',75,'Aventator',4,14,'Aventator LP 780-4 Ultimate',75,14,13,13,NULL,1,'Automatic',6498,780,12,1,'Petrol',NULL,NULL,NULL,NULL);
INSERT INTO `` (`id_brand`,`description`,`id_model`,`description`,`id_brand`,`id_variant`,`description`,`id_model`,`id_variant`,`id_engine`,`id_engine`,`description`,`id_fuel`,`transmission`,`capacity`,`power`,`cylinders`,`id_fuel`,`description`,`id_variant`,`id_feature`,`id_feature`,`description`) VALUES (4,'Lamborghini',76,'Huracan',4,15,'Huracán',76,15,16,16,NULL,1,'Automatic Tiptronic',5204,610,10,1,'Petrol',NULL,NULL,NULL,NULL);
INSERT INTO `` (`id_brand`,`description`,`id_model`,`description`,`id_brand`,`id_variant`,`description`,`id_model`,`id_variant`,`id_engine`,`id_engine`,`description`,`id_fuel`,`transmission`,`capacity`,`power`,`cylinders`,`id_fuel`,`description`,`id_variant`,`id_feature`,`id_feature`,`description`) VALUES (4,'Lamborghini',76,'Huracan',4,16,'Huracán Spyder',76,16,20,20,NULL,1,'Semi-Automatic',5204,610,10,1,'Petrol',NULL,NULL,NULL,NULL);
INSERT INTO `` (`id_brand`,`description`,`id_model`,`description`,`id_brand`,`id_variant`,`description`,`id_model`,`id_variant`,`id_engine`,`id_engine`,`description`,`id_fuel`,`transmission`,`capacity`,`power`,`cylinders`,`id_fuel`,`description`,`id_variant`,`id_feature`,`id_feature`,`description`) VALUES (4,'Lamborghini',76,'Huracan',4,17,'Huracán RWD',76,17,14,14,NULL,1,'Automatic',5204,580,10,1,'Petrol',NULL,NULL,NULL,NULL);
INSERT INTO `` (`id_brand`,`description`,`id_model`,`description`,`id_brand`,`id_variant`,`description`,`id_model`,`id_variant`,`id_engine`,`id_engine`,`description`,`id_fuel`,`transmission`,`capacity`,`power`,`cylinders`,`id_fuel`,`description`,`id_variant`,`id_feature`,`id_feature`,`description`) VALUES (4,'Lamborghini',76,'Huracan',4,18,'Huracán Performante',76,18,18,18,NULL,1,'Automatic',5204,640,10,1,'Petrol',NULL,NULL,NULL,NULL);
INSERT INTO `` (`id_brand`,`description`,`id_model`,`description`,`id_brand`,`id_variant`,`description`,`id_model`,`id_variant`,`id_engine`,`id_engine`,`description`,`id_fuel`,`transmission`,`capacity`,`power`,`cylinders`,`id_fuel`,`description`,`id_variant`,`id_feature`,`id_feature`,`description`) VALUES (4,'Lamborghini',76,'Huracan',4,19,'Huracán EVO',76,19,17,17,NULL,1,'DCT',5204,640,10,1,'Petrol',NULL,NULL,NULL,NULL);
INSERT INTO `` (`id_brand`,`description`,`id_model`,`description`,`id_brand`,`id_variant`,`description`,`id_model`,`id_variant`,`id_engine`,`id_engine`,`description`,`id_fuel`,`transmission`,`capacity`,`power`,`cylinders`,`id_fuel`,`description`,`id_variant`,`id_feature`,`id_feature`,`description`) VALUES (4,'Lamborghini',76,'Huracan',4,20,'Huracán EVO STO',76,20,17,17,NULL,1,'DCT',5204,640,10,1,'Petrol',NULL,NULL,NULL,NULL);
INSERT INTO `` (`id_brand`,`description`,`id_model`,`description`,`id_brand`,`id_variant`,`description`,`id_model`,`id_variant`,`id_engine`,`id_engine`,`description`,`id_fuel`,`transmission`,`capacity`,`power`,`cylinders`,`id_fuel`,`description`,`id_variant`,`id_feature`,`id_feature`,`description`) VALUES (4,'Lamborghini',76,'Huracan',4,21,'Huracán Sterrato',76,21,20,20,NULL,1,'Semi-Automatic',5204,610,10,1,'Petrol',NULL,NULL,NULL,NULL);
INSERT INTO `` (`id_brand`,`description`,`id_model`,`description`,`id_brand`,`id_variant`,`description`,`id_model`,`id_variant`,`id_engine`,`id_engine`,`description`,`id_fuel`,`transmission`,`capacity`,`power`,`cylinders`,`id_fuel`,`description`,`id_variant`,`id_feature`,`id_feature`,`description`) VALUES (4,'Lamborghini',77,'Gallardo',4,22,'Gallardo',77,22,24,24,NULL,1,'Automatic',4961,552,10,1,'Petrol',NULL,NULL,NULL,NULL);
INSERT INTO `` (`id_brand`,`description`,`id_model`,`description`,`id_brand`,`id_variant`,`description`,`id_model`,`id_variant`,`id_engine`,`id_engine`,`description`,`id_fuel`,`transmission`,`capacity`,`power`,`cylinders`,`id_fuel`,`description`,`id_variant`,`id_feature`,`id_feature`,`description`) VALUES (4,'Lamborghini',77,'Gallardo',4,23,'Gallardo Spyder',77,23,22,22,NULL,1,'Semi-Automatic',4961,552,10,1,'Petrol',NULL,NULL,NULL,NULL);
INSERT INTO `` (`id_brand`,`description`,`id_model`,`description`,`id_brand`,`id_variant`,`description`,`id_model`,`id_variant`,`id_engine`,`id_engine`,`description`,`id_fuel`,`transmission`,`capacity`,`power`,`cylinders`,`id_fuel`,`description`,`id_variant`,`id_feature`,`id_feature`,`description`) VALUES (4,'Lamborghini',78,'Heritage',4,24,'Heritage',78,24,28,28,NULL,1,'Semi-Automatic',3996,666,8,1,'Petrol',NULL,NULL,NULL,NULL);
INSERT INTO `` (`id_brand`,`description`,`id_model`,`description`,`id_brand`,`id_variant`,`description`,`id_model`,`id_variant`,`id_engine`,`id_engine`,`description`,`id_fuel`,`transmission`,`capacity`,`power`,`cylinders`,`id_fuel`,`description`,`id_variant`,`id_feature`,`id_feature`,`description`) VALUES (4,'Lamborghini',79,'Limited Series',4,25,'Centenario Roadster',79,25,25,25,NULL,1,'Semi-Automatic',6498,770,12,1,'Petrol',NULL,NULL,NULL,NULL);
INSERT INTO `` (`id_brand`,`description`,`id_model`,`description`,`id_brand`,`id_variant`,`description`,`id_model`,`id_variant`,`id_engine`,`id_engine`,`description`,`id_fuel`,`transmission`,`capacity`,`power`,`cylinders`,`id_fuel`,`description`,`id_variant`,`id_feature`,`id_feature`,`description`) VALUES (4,'Lamborghini',79,'Limited Series',4,26,'Sián FKP 37',79,26,25,25,NULL,1,'Semi-Automatic',6498,770,12,1,'Petrol',NULL,NULL,NULL,NULL);
